### ISSUE TITLE
Base images don't be optimized

### ISSUE THREAD

**Issue by danielchicote** [TinyPNG/magento-plugin#2]
Hello, your module is excelent and i love it. But i have an strange behavour with the optimization.

I have activated base images and small images for my pngs, but the base images never are optimizated and in the logs are completly ignored, i don't have any king error message. The small images works perfect for me in two sizes, and don't need thumbnails and swatches and there are always desactivated.

BUT if i activate the thumbnail images optimization, in these moment the base images starts to be optimizated ¿WTF?

Thanks

**Comment by tig-michielgerritsen** [comment]
Hello @danielchicote,

Thanks for your feedback. We have tested this in an plain Magento 1.9.2.4 webshop with version 2.0.1 installed, but there seems that everything is working fine. Can you provide us the following information so we can investigate this further:

- Used Magento version.
- Installed extensions in your Magento shop.
- The version of the extension you used.
